import type { BodyRegion, PrehabContext, PrehabDrill } from "./types";

export const DRILL_LIBRARY: Record<string, PrehabDrill> = {
  "band-pull-apart": {
    id: "band-pull-apart",
    name: "Band Pull-Aparts",
    category: "activation",
    regions: ["shoulder", "thoracic"],
    icon: "🪃",
    cue: "Band auf Brusthöhe ziehen & Schulterblätter zusammen",
    description:
      "Band vor dir halten, auf Armlänge auseinanderziehen bis es die Brust berührt. Aktiviert Rhomboideus & hinterer Schulter für stabile Bankposition.",
    durationSeconds: 45,
  },
  "face-pull-band": {
    id: "face-pull-band",
    name: "Face Pulls mit Band",
    category: "activation",
    regions: ["shoulder", "thoracic"],
    icon: "🎯",
    cue: "Band zum Gesicht, Ellenbogen hoch, Außenrotation am Ende",
    description:
      "Band auf Augenhöhe fixieren und zum Gesicht ziehen. Rotator Cuff & untere Trap werden aktiviert – Schutz für schwere Druckbewegungen.",
    durationSeconds: 45,
  },
  "thoracic-extension-roller": {
    id: "thoracic-extension-roller",
    name: "BWS-Mobilisation auf der Rolle",
    category: "mobility",
    regions: ["thoracic"],
    icon: "🧵",
    cue: "Rolle unter dem Brustkorb, sanft überstrecken",
    description:
      "Foam Roller im oberen Rücken ablegen, Hände hinterm Kopf und langsam über die Rolle strecken. Bringt die Brustwirbelsäule in Extension für sicheres Drücken.",
    durationSeconds: 50,
  },
  "wall-slide": {
    id: "wall-slide",
    name: "Wall Slides",
    category: "activation",
    regions: ["shoulder", "thoracic"],
    icon: "🧱",
    cue: "Unterarme an der Wand, langsam nach oben gleiten",
    description:
      "Rücken, Kopf und Arme an der Wand, Ellbogen auf Schulterhöhe. Langsam hochschieben ohne Kontakt zu verlieren – mobilisiert BWS & trainiert Aufwärtsrotation.",
    durationSeconds: 45,
  },
  "wrist-mobility": {
    id: "wrist-mobility",
    name: "Handgelenks-Mobilisation",
    category: "mobility",
    regions: ["wrist", "forearm"],
    icon: "✋",
    cue: "Kreise, Beugen & Strecken beider Handgelenke",
    description:
      "Handgelenke in alle Richtungen kreisen, dann Palm-up/palm-down dehnen. Bereitet Handgelenke auf Last im Überkopf- und Bankdrücken vor.",
    durationSeconds: 40,
  },
  "scap-pull": {
    id: "scap-pull",
    name: "Scap Pulls (hängend)",
    category: "activation",
    regions: ["shoulder", "thoracic"],
    icon: "🪝",
    cue: "In den Hang hängen, Schulterblätter aktiv nach unten ziehen",
    description:
      "An der Stange hängen und nur über die Schulterblätter den Körper minimal anheben. Schaltet Lat & Serratus für Züge ein.",
    durationSeconds: 40,
  },
  "cat-cow": {
    id: "cat-cow",
    name: "Cat-Cow Flow",
    category: "mobility",
    regions: ["lowerBack", "thoracic"],
    icon: "🐈",
    cue: "Rund machen & hohl kreuzen, mit dem Atem",
    description:
      "Im Vierfüßlerstand Wirbelsäule Segment für Segment bewegen. Lockert LWS & BWS vor jeder Belastung.",
    durationSeconds: 45,
  },
  "hip-9090-switch": {
    id: "hip-9090-switch",
    name: "90/90 Hüftwechsel",
    category: "mobility",
    regions: ["hip", "glute"],
    icon: "📐",
    cue: "Beine zu 90/90 lagern, kontrolliert die Seite wechseln",
    description:
      "Sitzend innere & äußere Hüftrotation abwechselnd durchbewegen. Öffnet die Hüfte für tiefe Kniebeugen ohne Ausweichbewegung.",
    durationSeconds: 50,
  },
  "ankle-dorsiflexion-rock": {
    id: "ankle-dorsiflexion-rock",
    name: "Knöchel-Dorsalflexion an der Wand",
    category: "mobility",
    regions: ["ankle"],
    icon: "🦶",
    cue: "Knie Richtung Wand schieben, Ferse bleibt am Boden",
    description:
      "Halbfußabstand vor der Wand, Knie kontrolliert über den Zehen zur Wand pumpen. Mehr Knöchelbeweglichkeit = tiefere, aufrechtere Squat-Position.",
    durationSeconds: 45,
  },
  "glute-bridge": {
    id: "glute-bridge",
    name: "Glute Bridges",
    category: "activation",
    regions: ["glute", "hip"],
    icon: "🌉",
    cue: "Hüfte aktiv hochdrücken, Gesäß fest am Top",
    description:
      "Rückenlage, Fersen nah am Po, Hüfte anheben und oben 1–2 Sekunden halten. Weckt die Glutes, damit sie statt des unteren Rückens arbeiten.",
    durationSeconds: 45,
  },
  "adductor-frog-rock": {
    id: "adductor-frog-rock",
    name: "Adductor Rocking (Frog Rocks)",
    category: "mobility",
    regions: ["adductor", "hip"],
    icon: "🐸",
    cue: "Aus der Frog-Position sanft in die Hüfte rocken",
    description:
      "Knie breit, Unterschenkel parallel, Gewicht sanft nach hinten-in-die-Hüfte schwingen. Mobilisiert Adduktoren für tiefe Breite in der unteren Squat-Phase.",
    durationSeconds: 45,
  },
  "worlds-greatest-stretch": {
    id: "worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    category: "mobility",
    regions: ["hip", "thoracic", "hamstring"],
    icon: "🌍",
    cue: "Ausfallschritt, Ellbogen zum Boden, Rotation nach oben",
    description:
      "Tiefer Ausfallschritt mit Ellenbogen-Tap und Thorax-Rotation. Ganzkörper-Mobility in einer Bewegung – Hüfte, Hamstrings & Drehbarkeit.",
    durationSeconds: 55,
  },
  "hip-flexor-opener": {
    id: "hip-flexor-opener",
    name: "Hüftbeuger-Öffner (Kneeling Opener)",
    category: "mobility",
    regions: ["hipFlexor", "quad"],
    icon: "🏹",
    cue: "Knien, Becken aufrichten, vorderes Bein nach vorn schieben",
    description:
      "Halber Kniestand, Gesäß anspannen und Becken nach vorn kippen. Verlängert verkürzte Hüftbeuger vom Radfahren und verbessert die Kraftebene.",
    durationSeconds: 50,
  },
  "hamstring-dynamic-swing": {
    id: "hamstring-dynamic-swing",
    name: "Dynamische Hamstring Swings",
    category: "mobility",
    regions: ["hamstring"],
    icon: "🦵",
    cue: "Gestrecktes Bein kontrolliert vor & zurück schwingen",
    description:
      "Stehend Beine dynamisch aber kontrolliert schwingen. Erwärmt die Hamstrings über den vollen Bewegungsradius – ideal vor Intervallen.",
    durationSeconds: 45,
  },
  "activation-spin": {
    id: "activation-spin",
    name: "Aktivations-Spins",
    category: "activation",
    regions: ["hip", "quad", "calf"],
    icon: "⚙️",
    cue: "Leichter Gang, hohe Frequenz ~100 rpm entspannt treten",
    description:
      "Auf der Rolle oder Straße: kleiner Gang, hohe Trittfrequenz, kaum Widerstand. Bringt Kreislauf & Pedaltechnik auf Betriebstemperatur.",
    durationSeconds: 60,
  },
  "walking-lunge-rotation": {
    id: "walking-lunge-rotation",
    name: "Ausfallschritt mit Rotation",
    category: "raise",
    regions: ["hip", "quad", "thoracic"],
    icon: "🔁",
    cue: "Schritt nach vorn, tief gehen, Oberkörper zur Seite drehen",
    description:
      "Walking Lunge kombiniert mit Rumpfrotation. Erhöht Puls und mobilisiert Hüftbeuger & BWS gleichzeitig.",
    durationSeconds: 50,
  },
  "leg-swings-side": {
    id: "leg-swings-side",
    name: "Beinschwünge seitlich",
    category: "mobility",
    regions: ["adductor", "hamstring", "hip"],
    icon: "↔️",
    cue: "Seitlich-wippend schwingen, Oberkörper ruhig halten",
    description:
      "Seitliche Beinschwünge öffnen Adduktoren & Hamstrings dynamisch – perfekt vor Lauf- oder Radintervallen.",
    durationSeconds: 40,
  },
  "calf-pump-step": {
    id: "calf-pump-step",
    name: "Wadenpumps an der Stufe",
    category: "activation",
    regions: ["calf", "ankle"],
    icon: "⬆️",
    cue: "Zehen Spitze & Ferse tief, federnd auf-ab",
    description:
      "Auf einer Stufe Fersen absenkend heben und senken. Aktiviert Waden & Achillessehnen für Laufökonomie.",
    durationSeconds: 40,
  },
  "a-skip": {
    id: "a-skip",
    name: "A-Skips",
    category: "raise",
    regions: ["hip", "ankle", "quad"],
    icon: "🏃",
    cue: "Knie hoch, Fuß aktiv abrollen, rhythmisch springen",
    description:
      "Laufschule A-Skip: koordiniert Hüftbeuger, Kniewinkel & Fußaufsatz – schaltet das Laufmuster scharf.",
    durationSeconds: 45,
  },
  "arm-circles": {
    id: "arm-circles",
    name: "Armkreisen",
    category: "raise",
    regions: ["shoulder"],
    icon: "🔄",
    cue: "Kleine zu großen Kreisen, vor- und rückwärts",
    description:
      "Arme gestreckt spiralförmig kreisen. Puls-raiser, der Schultergelenk & Brustkorb erwärmt.",
    durationSeconds: 40,
  },
  "deep-squat-hold": {
    id: "deep-squat-hold",
    name: "Deep Squat Hold",
    category: "mobility",
    regions: ["hip", "ankle", "adductor"],
    icon: "🏋️",
    cue: "In die Tiefe sinken, Ellbogen innen gegen Knie drücken",
    description:
      "Untere Squat-Position halten, mit Ellbogen die Knie sanft aufdrehen. Alltags-Basismobility für Hüfte, Knöchel & Adduktoren.",
    durationSeconds: 50,
  },
  "hamstring-floss": {
    id: "hamstring-floss",
    name: "Hamstring Floss",
    category: "mobility",
    regions: ["hamstring"],
    icon: "🪢",
    cue: "Bein strecken & Beuge-Knie abwechseln, nervenschonend flossig",
    description:
      "Rückenlage oder stehend: Knie strecken während der Fuß zum Schienbein zieht, dann wechseln. Mobilisiert Hamstrings inklusive Nervenbahnen bei Verspannung.",
    durationSeconds: 45,
  },
  "band-external-rotation": {
    id: "band-external-rotation",
    name: "Rotator Cuff Außenrotation mit Band",
    category: "activation",
    regions: ["shoulder"],
    icon: "🌀",
    cue: "Ellbogen am Körper, Hand langsam nach außen rotieren",
    description:
      "Gezielte Isolation der Infraspinatus/Teres minor. Pflichtprogramm wenn die Schulter am Vortag gezwickt hat.",
    durationSeconds: 45,
  },
  "monster-walk-band": {
    id: "monster-walk-band",
    name: "Monster Walks mit Band",
    category: "activation",
    regions: ["glute", "hip"],
    icon: "🚶",
    cue: "Band um Knie, seitwärts gehen, Knie außen",
    description:
      "Seitliche Schritte gegen das Band aktivieren Gluteus medius – stabilisiert Hüfte & Knietrack bei bestehender Hüftverspannung.",
    durationSeconds: 45,
  },
  "butterfly-stretch": {
    id: "butterfly-stretch",
    name: "Schmetterlingsdehnen",
    category: "mobility",
    regions: ["adductor", "hip"],
    icon: "🦋",
    cue: "Fußsohlen zusammen, Knie Richtung Boden lenken",
    description:
      "Sanftes statisches Öffnen der Innenseite. Gezielt bei Leisten- oder Adduktorzwicken vom Vortag.",
    durationSeconds: 45,
  },
  "kneeling-quad-stretch": {
    id: "kneeling-quad-stretch",
    name: "Kneeling Quad Stretch",
    category: "mobility",
    regions: ["quad", "knee"],
    icon: "🧎",
    cue: "Knien, Ferse zum Po, Becken gerade halten",
    description:
      "Vorderer Oberschenkel verlängern, wenn der Quadrizeps verspannt ist – entlastet zugleich den Kniestreckapparat.",
    durationSeconds: 45,
  },
  "tibialis-knee-circles": {
    id: "tibialis-knee-circles",
    name: "Tibialis Raises & Kniekreise",
    category: "activation",
    regions: ["knee", "ankle"],
    icon: "🦴",
    cue: "Zehenspitzen anheben, dann Knie langsam kreisen",
    description:
      "Schienbeinmuskel aktivieren und Kniegelenk einfahren – Basis-Prehab bei Knizwicken oder druckempfindlichen Knien.",
    durationSeconds: 40,
  },
  "ball-foot-roll": {
    id: "ball-foot-roll",
    name: "Fußsohlen-Roll mit Ball",
    category: "mobility",
    regions: ["ankle"],
    icon: "⚽",
    cue: "Ball unter der Fußsohle langsam von Ferse zu Zehen rollen",
    description:
      "Plantare Fascie und Fußmuskulatur lockern – wichtig bei Knöchelsteifheit oder viel Zeit auf harten Sohlen.",
    durationSeconds: 45,
  },
  "wall-calf-stretch": {
    id: "wall-calf-stretch",
    name: "Wadendehnen an der Wand",
    category: "mobility",
    regions: ["calf", "ankle"],
    icon: "🧗",
    cue: "Hacken fest am Boden, Hüfte Richtung Wand schieben",
    description:
      "Gastrocnemius & Soleus verlängern – Pflicht wenn die Waden nach gestrigem Training spannen.",
    durationSeconds: 45,
  },
  "bird-dog": {
    id: "bird-dog",
    name: "Bird Dog",
    category: "activation",
    regions: ["lowerBack"],
    icon: "🐕",
    cue: "Kontralaterale Arme/Beine lang ausstrecken, Hüfte stabil",
    description:
      "Anti-Rotations-Stabilität für die Lendenwirbelsäule. Ideal wenn der untere Rücken vom Vortag empfindlich reagiert.",
    durationSeconds: 45,
  },
  "thread-the-needle": {
    id: "thread-the-needle",
    name: "Thread the Needle",
    category: "mobility",
    regions: ["thoracic"],
    icon: "🪡",
    cue: "Arm unter dem Körper hindurch, dann zur Decke drehen",
    description:
      "Segmentale BWS-Rotation – löst Verspannungen im oberen Rücken zwischen den Schulterblättern.",
    durationSeconds: 45,
  },
  "forearm-wrist-stretch": {
    id: "forearm-wrist-stretch",
    name: "Unterarm-Dehnen",
    category: "mobility",
    regions: ["forearm", "wrist"],
    icon: "🤲",
    cue: "Handfläche & Handrücken je 20s statisch dehnen",
    description:
      "Flexoren und Extensoren verlängern – gezielt bei Handgelenks- oder Unterarmbeschwerden vom Vortag.",
    durationSeconds: 45,
  },
  "doorway-pec-stretch": {
    id: "doorway-pec-stretch",
    name: "Brustdehnen im Türrahmen",
    category: "mobility",
    regions: ["chest", "shoulder"],
    icon: "🚪",
    cue: "Unterarm am Rahmen, Brustkorb sanft durch den Rahmen",
    description:
      "Pectoralis major/minor öffnen – kontert verkürzte Brustmuskulatur bei Brustverspannung oder Drucklast vom Vortag.",
    durationSeconds: 45,
  },
};

export const BASE_SEQUENCES: Record<PrehabContext, string[]> = {
  "upper-push": [
    "band-pull-apart",
    "face-pull-band",
    "thoracic-extension-roller",
    "wall-slide",
    "wrist-mobility",
  ],
  "upper-pull": ["scap-pull", "band-pull-apart", "cat-cow", "thread-the-needle"],
  "lower-body": [
    "hip-9090-switch",
    "ankle-dorsiflexion-rock",
    "glute-bridge",
    "adductor-frog-rock",
    "worlds-greatest-stretch",
  ],
  "cycling-intervals": [
    "hip-flexor-opener",
    "hamstring-dynamic-swing",
    "leg-swings-side",
    "walking-lunge-rotation",
    "activation-spin",
  ],
  "cycling-endurance": [
    "hip-flexor-opener",
    "hamstring-dynamic-swing",
    "activation-spin",
  ],
  running: ["hip-flexor-opener", "leg-swings-side", "calf-pump-step", "a-skip"],
  general: ["cat-cow", "worlds-greatest-stretch", "deep-squat-hold", "arm-circles"],
};

export const SORENESS_EXTRA_DRILLS: Partial<Record<BodyRegion, string[]>> = {
  hamstring: ["hamstring-floss"],
  shoulder: ["band-external-rotation"],
  hip: ["monster-walk-band"],
  hipFlexor: ["hip-flexor-opener"],
  glute: ["monster-walk-band"],
  adductor: ["butterfly-stretch"],
  quad: ["kneeling-quad-stretch"],
  knee: ["tibialis-knee-circles"],
  ankle: ["ball-foot-roll"],
  calf: ["wall-calf-stretch"],
  lowerBack: ["bird-dog"],
  thoracic: ["thread-the-needle"],
  wrist: ["forearm-wrist-stretch"],
  forearm: ["forearm-wrist-stretch"],
  chest: ["doorway-pec-stretch"],
};
